Update Cache to support Constant Multiple
OasisDEX/oasis-borrow-cache pull request #132
Opened 2022-07-26 07:19 UTC by halaprix

[Update Cache to support Constant Multiple](https://app.shortcut.com/oazo-apps/story/5354/update-cache-to-support-constant-multiple)

2022-07-26 08:10 UTC, paszkowskiDamian commented on src/borrow/transformers/automationAggregatorBotTransformer.ts
> +  });
Can you add values in one go? 

Also all promises inside should be awaited, because we might miss some rejected promises without noticing.

2022-07-26 08:14 UTC, paszkowskiDamian commented on src/borrow/transformers/automationAggregatorBotTransformer.ts
> +    ),
This dependency is not necessary. It would be if you have read from multiply table.

2022-08-01 10:42 UTC, johnnieskywalker commented on src/borrow/migrations/035-automation-aggregator-bot.sql
> +select b.group_id,
minor - make it all consistently formatted, capital letters etc.

2022-08-01 10:42 UTC, johnnieskywalker commented on src/borrow/transformers/automationAggregatorBotTransformer.ts
> +  console.log(values.group_type);
Before merging remove console.logs please

2022-08-02 09:43 UTC, rkrasiuk requested changes
trigger groups should be consistent w/ triggers and should not bear information about trigger types

2022-08-02 09:43 UTC, rkrasiuk commented on src/borrow/transformers/automationAggregatorBotTransformer.ts
> +  }
what's happening here?

2022-08-02 09:47 UTC, halaprix commented on src/borrow/transformers/automationAggregatorBotTransformer.ts
> +  }
for group_type == 1 update data is created that is later updated into `automation_bot.trigger_added_events`.

First trigger gets index of 3 and second gets 4.

Left it open for different group types - and it defaults to  1 = CM

2022-08-02 11:23 UTC, paszkowskiDamian commented on src/addresses/goerli.json
> +  "AUTOMATION_AGGREGATOR_BOT" : "0xf9342047D6f0e29D24b5bBA3BF79fC700D086A3d"
What about the previous addresses, by changing it here after recreating the cache we will miss events from previous contracts, is it intended?

2022-08-02 11:26 UTC, paszkowskiDamian commented on src/borrow/transformers/automationAggregatorBotTransformer.ts
> +    ['group_id', '?trigger_id'],
`?trigger_id`  with the question mark?

2022-08-02 11:27 UTC, paszkowskiDamian commented on src/borrow/transformers/automationAggregatorBotTransformer.ts
> +  await services.tx.none(triggerAddedEventsUpdateQuery);
As we discussed we cannot update previously created rows.

2022-08-02 11:30 UTC, paszkowskiDamian commented on src/borrow/transformers/automationAggregatorBotTransformer.ts
> +  });
It's just code style, but why don't you just use `Array.map`

```
const triggerAddedEventsUpdateData = values.trigger_id.map((element: number) => {
return {
      group_id: values.group_id,
      trigger_id: element,
}
})
```

2022-08-02 11:30 UTC, halaprix commented on src/addresses/goerli.json
> +  "AUTOMATION_AGGREGATOR_BOT" : "0xf9342047D6f0e29D24b5bBA3BF79fC700D086A3d"
that's why the [DO NOT MERGE] :) these are two dummy contracts that only emit event

2022-08-02 11:33 UTC, paszkowskiDamian commented on src/borrow/transformers/automationAggregatorBotTransformer.ts
> +  await services.tx.none(triggerAddedEventsUpdateQuery);
again, we cannot update it, we could make an exception if it was in the same block.

2022-08-02 11:42 UTC, paszkowskiDamian commented on src/borrow/transformers/automationAggregatorBotTransformer.ts
> +  // for constant multiple the first trigger type is 3 and second is 4 - hence index + 3
?

2022-08-02 12:47 UTC, paszkowskiDamian approved these changes

2022-08-04 11:05 UTC, merged