Update Automation Bot Info
OasisDEX/oasis-borrow-cache pull request #77
Opened 2022-01-19 14:05 UTC by rkrasiuk

2022-01-19 14:14 UTC, rkrasiuk commented
@adamskrodzki pls advice if it's worth changing the database column from `trigger_data` to `command_address`

2022-01-20 09:43 UTC, fenris85 approved these changes

2022-01-20 13:29 UTC, adamskrodzki requested changes

2022-01-20 13:29 UTC, adamskrodzki commented on abis/automation-bot.json
> +      { "indexed": true, "internalType": "address", "name": "commandAddress", "type": "address" },
I think this PR misses some changes, 

namely since triggerType was removed and 
commandAddress was added 

it affects IMHO structure of

automation_bot.trigger_added_events

and possibly requires some migration

2022-01-25 16:22 UTC, adamskrodzki requested changes

2022-01-25 16:25 UTC, adamskrodzki approved these changes

2022-01-25 16:26 UTC, merged

2022-01-27 17:37 UTC, adamskrodzki commented on src/borrow/migrations/017-automation-command-address.sql
> +    LEFT JOIN automation_bot.trigger_removed_events removed ON added.trigger_id = removed.trigger_id
This query is wirdly build, but in order to be correct it should have:
`added.trigger_id =< removed.trigger_id`