added trigger executed in migration script to db and added method sup…
OasisDEX/oasis-borrow-cache pull request #79
Opened 2022-02-08 15:28 UTC by johnnieskywalker

https://app.shortcut.com/oazo-apps/story/3494/handling-triggerexecuted-in-oasis-cache

added trigger executed in migration script to db and added method support in transformer

2022-02-08 15:32 UTC, johnnieskywalker commented on src/borrow/transformers/automationBotTransformer.ts
> +    const values = {
it's the same as in trigger removed so maybe could introduce a type here but I don't see any value added of doing so

2022-02-08 15:48 UTC, rkrasiuk commented on src/borrow/migrations/019-trigger-executed.sql
> +    log_index               integer not null,
indent properly pls

2022-02-08 15:48 UTC, rkrasiuk commented on src/borrow/transformers/automationBotTransformer.ts
> +    const values = {
you're right, no need to

2022-02-11 13:48 UTC, johnnieskywalker commented on src/borrow/transformers/automationBotTransformer.ts
> +    `INSERT INTO automation_bot.trigger_removed_events(
:O

2022-02-17 06:16 UTC, rkrasiuk commented on src/addresses/goerli.json
> +  "AUTOMATION_BOT": "0x8A08e91326Ac93fBcfcFb13912cEDdcb7Fc28f71"
how the fuck is this change in a diff?

2022-02-17 06:24 UTC, rkrasiuk requested changes

2022-02-17 06:24 UTC, rkrasiuk commented on src/borrow/migrations/019-trigger-executed.sql
> +    )
pls format this migration in the same fashion others are

2022-02-17 06:24 UTC, rkrasiuk commented on src/borrow/transformers/automationBotTransformer.ts
> +  };
pls, store the execution data as well

2022-02-17 06:24 UTC, rkrasiuk commented on src/borrow/transformers/automationBotTransformer.ts
> +  );
closeEventId is not set in `values` object, that's this query will always fail

2022-02-17 06:24 UTC, rkrasiuk commented on src/config.goerli.ts
> +    address: '0x24E54706B100e2061Ed67fAe6894791ec421B421',
please, add it either to `addresses/goerli.json` file or the `addresses` variable inside this file

2022-02-17 06:24 UTC, rkrasiuk commented on src/addresses/goerli.json
> +  "AUTOMATION_BOT": "0x8A08e91326Ac93fBcfcFb13912cEDdcb7Fc28f71"
i wonder if github can't diff anymore heh

2022-02-17 16:07 UTC, johnnieskywalker commented on src/borrow/migrations/019-trigger-executed.sql
> +    )
done maually lmk if there's some formatter for vs code that does it default one is not satisfactory

2022-02-18 06:49 UTC, johnnieskywalker commented on src/borrow/transformers/automationBotTransformer.ts
> +  };
solved

2022-02-21 15:34 UTC, johnnieskywalker commented
As borrow vaults don't have close event this is how it looks in cache 
![image](https://user-images.githubusercontent.com/6871923/154985648-2ac830c6-e436-4c7b-9a03-0c118ce008db.png)

This is event 42 from this tx 
https://goerli.etherscan.io/tx/0x0e04a004827a7454eda4ee78966da94323fe11717249a4d505c6d855c7907419#eventlog

2022-02-23 08:24 UTC, johnnieskywalker commented on src/addresses/goerli.json
> +  "AUTOMATION_BOT": "0x8A08e91326Ac93fBcfcFb13912cEDdcb7Fc28f71",
Address will change once new smart contract will be redeployed containing this changes and others 
https://github.com/OasisDEX/automation-smartcontracts/pull/32/files

2022-02-23 08:40 UTC, johnnieskywalker commented on abis/automation-bot.json
> +        },
This ABI was edited manually this is change that will need to be deployed

2022-02-23 09:25 UTC, rkrasiuk requested changes

2022-02-23 09:25 UTC, rkrasiuk commented on src/borrow/transformers/automationBotTransformer.ts
> +    transformerDependencies: [...multiplyProxyActionsAddress.map(mpa => getMultiplyTransformerName(mpa))],
unnecessary spread
```suggestion
    transformerDependencies: multiplyProxyActionsAddress.map(mpa => getMultiplyTransformerName(mpa)),
```

2022-02-23 09:25 UTC, rkrasiuk commented on src/borrow/transformers/automationBotTransformer.ts
> +
nit: rm this empty line

2022-02-23 09:25 UTC, rkrasiuk commented on src/borrow/transformers/automationBotTransformer.ts
> +       kind = 'exit_collateral' or kind = 'exit_dai' and tx_id = ${log.tx_id}
fix logical precedence with parenthesis
https://www.postgresql.org/docs/7.2/sql-precedence.html

2022-02-23 10:43 UTC, johnnieskywalker commented on src/borrow/transformers/automationBotTransformer.ts
> +       kind = 'exit_collateral' or kind = 'exit_dai' and tx_id = ${log.tx_id}
thanks for this observation so I guess fix will look like:
```sql
SELECT * FROM vault.multiply_events me WHERE
       (kind = 'exit_collateral' or kind = 'exit_dai') and tx_id = ${log.tx_id}
      LIMIT 1;
```

2022-02-23 17:00 UTC, rkrasiuk approved these changes

2022-02-24 09:16 UTC, merged