deposit and multiply
OasisDEX/oasis-borrow-cache pull request #82
Opened 2022-03-04 13:46 UTC by piekczyk

2022-03-04 14:14 UTC, johnnieskywalker approved these changes

2022-03-14 08:55 UTC, adamskrodzki requested changes

2022-03-14 08:55 UTC, adamskrodzki commented on src/borrow/migrations/020-update-method-name-length.sql
> +CREATE VIEW api.vault_multiply_events AS (
what changed @piekczyk  ? in 009-multiply.sql i see axacly same view

2022-03-14 08:58 UTC, piekczyk commented on src/borrow/migrations/020-update-method-name-length.sql
> +CREATE VIEW api.vault_multiply_events AS (
its impossible to alter table when there is a view which depends on it

2022-03-14 09:38 UTC, adamskrodzki approved these changes

2022-03-14 09:41 UTC, merged