Added kind and type columns for all trigger events and created view trigger_events
OasisDEX/oasis-borrow-cache pull request #85
Opened 2022-03-15 17:34 UTC by johnnieskywalker

2022-03-16 10:15 UTC, adamskrodzki approved these changes

2022-03-16 10:15 UTC, adamskrodzki commented on src/borrow/migrations/022-automation-events-ddl-dml-kind-type.sql
> +	SET kind = 'stop-loss'
what is kind ? doesn't this table already have triggetTypeId?

2022-03-16 10:15 UTC, adamskrodzki commented on src/borrow/migrations/022-automation-events-ddl-dml-kind-type.sql
> +	SET event_type = 'added'
this do not need to sit in table, you can do this on view level

2022-03-16 10:15 UTC, adamskrodzki commented on src/borrow/migrations/022-automation-events-ddl-dml-kind-type.sql
> +	SELECT  id , trigger_id , cdp_id, tx_id , block_id, kind , event_type  from automation_bot.trigger_executed_events tee
`SELECT id , trigger_id , cdp_id, tx_id , block_id, kind , 'added' as event_type  from automation_bot.trigger_added_events tae
	UNION
	SELECT  id , trigger_id , cdp_id, tx_id , block_id, kind , 'removes' as event_type  from automation_bot.trigger_removed_events tre 
	UNION 
	SELECT  id , trigger_id , cdp_id, tx_id , block_id, kind , 'executed' as event_type  from automation_bot.trigger_executed_events tee`

2022-03-16 10:15 UTC, adamskrodzki commented on src/borrow/transformers/automationBotTransformer.ts
> +      trigger_id, cdp_id, command_address, trigger_data, log_index, tx_id, block_id, kind, event_type
what execly kind is needed for ?
triggerData includes triggerType and also command_address fully determines triggerType

2022-03-16 12:08 UTC, piekczyk commented on src/borrow/migrations/022-automation-events-ddl-dml-kind-type.sql
> +	SELECT  id , trigger_id , cdp_id, tx_id , block_id, kind , event_type  from automation_bot.trigger_executed_events tee
If we want to be consistent with other event interfaces you should include here urn, timestamp, log_index, hash - there may be more to include beside those. Take a look how query for multiply history view looks like.

https://github.com/OasisDEX/oasis-borrow/blob/dev/features/vaultHistory/vaultMultiplyHistory.ts#L14

With current column set (plus those that I mentioned) we will be able to show on the UI that event happen but without any details.

2022-03-16 12:20 UTC, piekczyk commented on src/borrow/migrations/022-automation-events-ddl-dml-kind-type.sql
> +	SET event_type = 'added'
If we use @Adam suggestion lets do it in the way that will be consistent with other history views. It means that kind should have format more or less like this STOP_LOSS_ADDED, STOP_LOSS_REMOVED, STOP_LOSS_EXECUTED.

2022-03-16 12:28 UTC, piekczyk commented on src/borrow/migrations/022-automation-events-ddl-dml-kind-type.sql
> +	SELECT  id , trigger_id , cdp_id, tx_id , block_id, kind , event_type  from automation_bot.trigger_executed_events tee
UNION does not ensure proper handling of ids which should be unique here. I guess we don't need to select ids here, rather generating unique ones in the scope of this view.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/39706811/158589635-b4547b04-63af-4fa7-ae18-7a79eea9de5e.png">

2022-03-17 12:58 UTC, johnnieskywalker commented on src/borrow/transformers/automationBotTransformer.ts
> +        \${trigger_id}, \${cdp_id}, \${close_event_id}, \${log_index}, \${tx_id}, \${block_id}, 'stop-loss', 'executed'
this inserts will no longer work, will fix

2022-03-17 15:39 UTC, johnnieskywalker commented on src/borrow/migrations/022-automation-events-ddl-dml-kind-type.sql
> +	SELECT  id , trigger_id , cdp_id, tx_id , block_id, kind , event_type  from automation_bot.trigger_executed_events tee
urn is fetched from blockchain see example here
https://github.com/OasisDEX/oasis-borrow-cache/blob/dev/src/borrow/dependencies/getUrnForCdp.ts

so I could add urn for each for ex. `trigger_added` record when the transformer is creating those I'd have to add urn column in that table I believe unless there's SQL way to get urn for cdpId

2022-03-18 08:38 UTC, adamskrodzki requested changes

2022-03-18 08:38 UTC, adamskrodzki commented on src/borrow/migrations/022-automation-events-ddl-kind-type.sql
> +	SELECT  tre.id , tre.trigger_id , tre.cdp_id, tre.log_index , tx.hash , b."number", b."timestamp" ,'removes' AS event_type, tae.command_address, alias.kind  from automation_bot.trigger_removed_event
not so important, but if 'added' and 'executed'  then i guess 'removed' not 'removes'

2022-03-18 08:38 UTC, adamskrodzki commented on src/config.goerli.ts
> +async function initializeCommandAliases(services: any) {
this function should not be here, in some common-utils instead

2022-03-18 08:38 UTC, adamskrodzki commented on src/config.goerli.ts
> +  await Promise.all(promises);
not sure if it will behave correctly for multiple entries if the same object db is reused in parallel.

2022-03-18 08:38 UTC, adamskrodzki commented on src/config.goerli.ts
> +  await Promise.all(promises);
I would use sequential for loop instead, maybe there is some concise syntax with forEach but I'm not sure.

2022-03-18 08:38 UTC, adamskrodzki commented on src/config.goerli.ts
> +  const promises = Object.entries(commandMapping).map(([key, value]) => {
take commandMapping as a parameter do not rely on scope.

2022-03-18 08:40 UTC, adamskrodzki commented on src/borrow/migrations/022-automation-events-ddl-dml-kind-type.sql
> +	SELECT  id , trigger_id , cdp_id, tx_id , block_id, kind , event_type  from automation_bot.trigger_executed_events tee
(triggerId,event_type) is unique key here but do we actually need uniq key in a view?

2022-03-18 08:54 UTC, paszkowskiDamian commented on src/config.goerli.ts
> +async function initializeCommandAliases(services: any) {
The type of services is probably `Services`

2022-03-18 08:59 UTC, paszkowskiDamian commented on src/config.goerli.ts
> +  await Promise.all(promises);
You can insert multiply rows like that
``` 
// vatTransformer.ts
const cs = new services.pg.helpers.ColumnSet(
        [
          'kind',
          'collateral_amount',
          'dai_amount',
          'urn',
          'timestamp',
          'tx_id',
          'block_id',
          'log_index',
          'rate',
          'ilk',
        ],
        {
          table: {
            table: 'events',
            schema: 'vault',
          },
        },
      );

      const query = services.pg.helpers.insert(events, cs);
      await services.tx.none(query);
```

2022-03-18 09:02 UTC, paszkowskiDamian commented on src/config.goerli.ts
> +  await Promise.all(promises);
Remember to either remove old entries or handle conflicts, postgres has this feature
```
INSERT INTO my_table (column1, column2)
VALUES
    (value1, value2),
    (value3, value4),
    (value5, value6),
    (value7, value8)
ON CONFLICT DO NOTHING;
```

2022-03-22 09:02 UTC, merged